### ISSUE TITLE
idk.

### ISSUE THREAD

**Issue by t0days** [Bammerbom/UltimateCore#14]
java.lang.NullPointerException
        at org.spongepowered.common.text.serializer.JsonTextSerializer.deserialize(JsonTextSerializer.java:48)
        at bammerbom.ultimatecore.sponge.utils.Messages.getFormatted(Messages.java:141)
        at bammerbom.ultimatecore.sponge.utils.Messages.getFormatted(Messages.java:185)
        at bammerbom.ultimatecore.sponge.utils.UsageGenerator.shortDescription(UsageGenerator.java:48)
        at bammerbom.ultimatecore.sponge.api.command.Command.getShortDescription(Command.java:91)
        at bammerbom.ultimatecore.sponge.config.CommandsConfig.postload(CommandsConfig.java:66)
        at bammerbom.ultimatecore.sponge.UltimateCore.onPostInit(UltimateCore.java:213)
        at org.spongepowered.common.event.listener.GamePostInitializationEventListener_UltimateCore_onPostInit24.handle(Unknown Source)
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301)
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330)
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:229)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:52)
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:800)
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
        at java.lang.Thread.run(Unknown Source)

**Comment by t0days** [comment]
**Another Error**


java.lang.NullPointerException
        at org.spongepowered.common.text.serializer.JsonTextSerializer.deserialize(JsonTextSerializer.java:48)
        at bammerbom.ultimatecore.sponge.utils.Messages.getFormatted(Messages.java:141)
        at bammerbom.ultimatecore.sponge.utils.Messages.getFormatted(Messages.java:185)
        at bammerbom.ultimatecore.sponge.utils.UsageGenerator.shortDescription(UsageGenerator.java:48)
        at bammerbom.ultimatecore.sponge.api.command.Command.getShortDescription(Command.java:91)
        at bammerbom.ultimatecore.sponge.config.CommandsConfig.postload(CommandsConfig.java:66)
        at bammerbom.ultimatecore.sponge.UltimateCore.onReload(UltimateCore.java:306)
        at bammerbom.ultimatecore.sponge.defaultmodule.commands.UltimatecoreCommand$ReloadCommand.execute(UltimatecoreCommand.java:180)
        at bammerbom.ultimatecore.sponge.api.command.SmartCommand.run(SmartCommand.java:82)
        at bammerbom.ultimatecore.sponge.api.command.SmartCommand.run(SmartCommand.java:69)
        at bammerbom.ultimatecore.sponge.impl.command.UCCommandCallable.process(UCCommandCallable.java:67)
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333)
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:295)
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83)
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913)
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892)
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156)
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39)
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.minecraft.util.Util.func_181617_a(SourceFile:45)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Unknown Source)

**Comment by JonathanBrouwer** [comment]
Can't reproduce.

Any idea when this happens?
UltimateCore version & Sponge version?
Any other mods?

**Comment by JonathanBrouwer** [comment]
Closed because of inactivity.
