### ISSUE TITLE
Could not pass InteractItemEvent$Secondary$MainHand$Impl

### ISSUE THREAD

**Issue by TomberWolf** [Bammerbom/UltimateCore#20]
```
[00:08:12] [Server thread/ERROR] [Sponge]: Could not pass InteractItemEvent$Secondary$MainHand$Impl to Plugin{id=ultimat
ecore, name=UltimateCore, version=3.0.8, description=All you need to set up a server and more!, url=http://ultimatecore.
org/index, authors=[Bammerbom], source=D:\Server\MinecraftWolfskraft110\.\plugins\UltimateCore-3.0.8ALPHA.jar}
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source) ~[?:1.8.0_121]
        at bammerbom.ultimatecore.sponge.modules.afk.listeners.AfkDetectionListener.unafkCheck(AfkDetectionListener.java
:139) ~[AfkDetectionListener.class:?]
        at bammerbom.ultimatecore.sponge.modules.afk.listeners.AfkDetectionListener.lambda$start$4(AfkDetectionListener.
java:93) ~[AfkDetectionListener.class:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.cla
ss:1.10.2-2254-5.2.0-BETA-2241]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager
.class:1.10.2-2254-5.2.0-BETA-2241]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342) [SpongeModEventManager
.class:1.10.2-2254-5.2.0-BETA-2241]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager
.class:1.10.2-2254-5.2.0-BETA-2241]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2254-5.2.0-BETA-2
241]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractItemEventSecondary(SpongeCommonEventFacto
ry.java:423) [SpongeCommonEventFactory.class:1.10.2-2254-5.2.0-BETA-2241]
        at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:254) [PacketUtil.class:1.10.2-2254-
5.2.0-BETA-2241]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:90) [PacketUtil.class:1.10.2-2254
-5.2.0-BETA-2241]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjf000(SourceFile:539) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:235) [SpongeImplHooks.class:1.10.
2-2254-5.2.0-BETA-2241]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhm000(MinecraftServer.java:3931) [MinecraftServer.class:
?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
>
```

**Comment by JonathanBrouwer** [comment]
I don't know what causes this exactly.
I think I fixed it, but I am not sure.
If it is not fixed, please re-open and give me context of the error (what did you do to trigger it)

**Comment by TomberWolf** [comment]
Where can I download the fixed version?

**Comment by JonathanBrouwer** [comment]
Woops forgot about that
http://www.mediafire.com/file/2j4ki426o62m2mn/UltimateCore.jar
