### ISSUE TITLE
Error: Could not pass SendCommandEvent

### ISSUE THREAD

**Issue by TomberWolf** [Bammerbom/UltimateCore#21]
I get errors as soons as I type a command - no matter if it's an UC command or an completely unkown command like /qwerty123 for example.

```
[01:55:24] [Server thread/ERROR] [Sponge]: Could not pass SendCommandEvent$Impl to Plugin{id=ultimat
ecore, name=UltimateCore, version=3.0.8, description=All you need to set up a server and more!, url=
http://ultimatecore.org/index, authors=[Bammerbom], source=D:\Server\MinecraftWolfskraft1-10-2\.\plu
gins\UltimateCore-3.0.8ALPHA.jar}
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source) ~[?:1.8.0_121]
        at bammerbom.ultimatecore.sponge.modules.afk.listeners.AfkDetectionListener.lambda$start$3(A
fkDetectionListener.java:81) ~[AfkDetectionListener.class:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[Re
gisteredListener.class:1.10.2-2254-5.2.0-BETA-2241]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) ~[
SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2241]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342) ~[
SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2241]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[
SpongeModEventManager.class:1.10.2-2254-5.2.0-BETA-2241]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:2
67) ~[SpongeCommandManager.class:1.10.2-2254-5.2.0-BETA-2241]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~
[me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~
[me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.cl
ass:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.cla
ss:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:158)
 ~[PacketUtil.class:1.10.2-2254-5.2.0-BETA-2241]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:157)
 [CauseTracker.class:1.10.2-2254-5.2.0-BETA-2241]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:157) [PacketU
til.class:1.10.2-2254-5.2.0-BETA-2241]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjf000(SourceFile:539)
[fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:235) [SpongeI
mplHooks.class:1.10.2-2254-5.2.0-BETA-2241]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhm000(MinecraftServer.java:3931) [Mi
necraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftSer
ver.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld
.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftSer
ver.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class
:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
>
```

**Comment by TomberWolf** [comment]
It was RedProtect.
