### ISSUE TITLE
Do not know why, every time you want to brush this newspaper wrong

### ISSUE THREAD

**Issue by qsxzaqq** [Bammerbom/UltimateCore#29]
[21:56:32] [Server thread/ERROR] [Sponge/]: The Scheduler tried to run the task UC afk title task owned by Plugin{id=ultimatecore, name=UltimateCore, version=3.0.11, description=All you need to set up a server and more!, url=http://ultimatecore.org/index, authors=[Bammerbom], source=/home/admin/桌面/hxsj/mods/UltimateCore.jar}, but an error occured.
java.lang.NullPointerException
	at org.spongepowered.common.text.serializer.JsonTextSerializer.deserialize(JsonTextSerializer.java:58) ~[JsonTextSerializer.class:1.10.2-2281-5.2.0-BETA-2353]
	at bammerbom.ultimatecore.sponge.api.language.impl.UCLanguageService.getMessage(UCLanguageService.java:82) ~[UCLanguageService.class:?]
	at bammerbom.ultimatecore.sponge.api.language.utils.Messages.getFormatted(Messages.java:64) ~[Messages.class:?]
	at bammerbom.ultimatecore.sponge.modules.afk.runnables.AfkTitleTask.run(AfkTitleTask.java:46) ~[AfkTitleTask.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.10.2-2281-5.2.0-BETA-2353]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2353]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:81) ~[SyncScheduler.class:1.10.2-2281-5.2.0-BETA-2353]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2353]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2353]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_65]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2353]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:51) [SyncScheduler.class:1.10.2-2281-5.2.0-BETA-2353]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-2281-5.2.0-BETA-2353]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:271) [SpongeMod.class:1.10.2-2281-5.2.0-BETA-2353]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

Solution method

**Comment by JonathanBrouwer** [comment]
Are you using a language other than english?
Try selecting the english language file, if so.
Try resetting your english language file if the problem persists.

**Comment by qsxzaqq** [comment]
OK,I'm in China, so I want to change my documents

**Comment by JonathanBrouwer** [comment]
Got any results?
