### ISSUE TITLE
offline inventiry does not work

### ISSUE THREAD

**Issue by insert3coins** [Bammerbom/UltimateCore#3]
here's the error log
# 

UltimateCore has run into an error 

Bukkit version: git-Spigot-b73910a-726656b (MC: 1.8)

UltimateCore version: 2.0.4
Plugins loaded (3): [Vault v1.5.2-b33, UltimateCore v2.0.4, PermissionsEx v1.23.1]
Java version: 1.7.0_67

Error message: String index out of range: 31
# UltimateCore message: Failed to execute command: /inv **tehface**

Stacktrace: 
java.lang.StringIndexOutOfBoundsException: String index out of range: 31
    at java.lang.String.substring(Unknown Source)
    at bammerbom.ultimatecore.bukkit.resources.utils.InventoryUtil.convertStringToInventory(InventoryUtil.java:237)
    at bammerbom.ultimatecore.bukkit.api.UPlayer.getLastInventory(UPlayer.java:522)
    at bammerbom.ultimatecore.bukkit.commands.CmdInventory.run(CmdInventory.java:83)
    at bammerbom.ultimatecore.bukkit.UltimateCommands.onCmd(UltimateCommands.java:191)
    at bammerbom.ultimatecore.bukkit.UltimateCore.onCommand(UltimateCore.java:147)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
    at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
    at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
    at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
    at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
    at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
    at java.lang.Thread.run(Unknown Source)
#

**Comment by JonathanBrouwer** [comment]
Fixed.

**Comment by insert3coins** [comment]
thanks... ok so it works now sorta... does offline not allow editing? ie removing and putting in items, when i try to remove something it just wiggles a bit and won't let me move it, might be a permissions? i can't see one in the source

**Comment by JonathanBrouwer** [comment]
You are right, it does not allow editing. 

Is in todo list.

**Comment by insert3coins** [comment]
excellent look forward to it.. and thanks :)

**Comment by insert3coins** [comment]
wondering if/when it will be added? ( sorry trying not to nag, but a feature i kinda want to see happen .. now lol ) thanks

**Comment by JonathanBrouwer** [comment]
My todo list is so huge, and I am currently busy with bug fixes and ip banning, so dont except it soon
