### ISSUE TITLE
Spam error — Could not pass ClientPingServerEvent$Impl

### ISSUE THREAD

**Issue by byrnane** [Bammerbom/UltimateCore#39]
Using:
Minecraft **1.12.2**
Forge on server&client **14.23.3.2690**
Sponge **7.1.0-BETA-3112**
Ultimatecore **latest**

System:
Allocated RAM: 3G
Windows 10
JRE 1.8.0_172

After some player left the game the server is starting to spam this error:
`[Netty Server IO #2/ERROR] [Sponge]: Could not pass ClientPingServerEvent$Impl to Plugin{id=ultimatecore, name=UltimateCore, version=3.0.12, description=All you need to set up a server and more!, url=http://ultimatecore.org/index, authors=[Bammerbom], source=.\mods\UltimateCore.jar}
java.lang.NoClassDefFoundError: dependencies/bammerbom/ultimatecore/net/minecrell/statusprotocol/StatusProtocol
	at bammerbom.ultimatecore.sponge.modules.serverlist.listeners.ServerlistListener.onMotdSend(ServerlistListener.java:99) ~[ServerlistListener.class:?]
	at org.spongepowered.common.event.listener.ClientPingServerEventListener_ServerlistListener_onMotdSend39.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2690-7.1.0-BETA-3112]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:374) [SpongeModEventManager.class:1.12.2-2690-7.1.0-BETA-3112]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:408) [SpongeModEventManager.class:1.12.2-2690-7.1.0-BETA-3112]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:392) [SpongeModEventManager.class:1.12.2-2690-7.1.0-BETA-3112]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:442) [SpongeEventManager.class:1.12.2-2690-7.1.0-BETA-3112]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2690-7.1.0-BETA-3112]
	at org.spongepowered.common.network.status.SpongeStatusResponse.call(SpongeStatusResponse.java:72) [SpongeStatusResponse.class:1.12.2-2690-7.1.0-BETA-3112]
	at org.spongepowered.common.network.status.SpongeStatusResponse.post(SpongeStatusResponse.java:55) [SpongeStatusResponse.class:1.12.2-2690-7.1.0-BETA-3112]
	at net.minecraft.server.network.NetHandlerStatusServer.func_147312_a(SourceFile:561) [pd.class:?]
	at net.minecraft.network.status.client.CPacketServerQuery.func_148833_a(SourceFile:23) [mw.class:?]
	at net.minecraft.network.status.client.CPacketServerQuery.func_148833_a(SourceFile:8) [mw.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147) [gw.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49) [gw.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [minecraft_server.1.12.2.jar:?]
	at net.minecraft.network.LegacyPingHandler.channelRead(SourceFile:601) [ox.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [minecraft_server.1.12.2.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.ClassNotFoundException: dependencies.bammerbom.ultimatecore.net.minecrell.statusprotocol.StatusProtocol
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	... 48 more
Caused by: java.lang.NullPointerException`

Full log is [here](https://gist.github.com/byrnane/403930a51c2452e0da87c23c8d3d46b6#file-log)

**Comment by gutasiadam** [comment]
Same here!

**Comment by sintaxcz** [comment]
Same Spam on forge 2705 and sponge 1.12.2-2705-7.1.0-BETA-3361 with UltimateCore v3.0.12
