### ISSUE TITLE
1.13 lots of errors

### ISSUE THREAD

**Issue by dudullle** [Bammerbom/UltimateCore#41]
**At startup**
`[UC] Failed minecraft:air`
**When using /warp command (/tp or /home are doing the same error type)**
`[19:41:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'warp' in plugin UltimateCore v2.1.25
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.jar:git-Paper-129]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.jar:git-Paper-129]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:724) ~[patched_1.13.jar:git-Paper-129]
        at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1752) ~[patched_1.13.jar:git-Paper-129]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1556) ~[patched_1.13.jar:git-Paper-129]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.jar:git-Paper-129]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.jar:git-Paper-129]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.jar:git-Paper-129]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) ~[patched_1.13.jar:git-Paper-129]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:987) ~[patched_1.13.jar:git-Paper-129]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-129]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:915) ~[patched_1.13.jar:git-Paper-129]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:813) ~[patched_1.13.jar:git-Paper-129]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoSuchFieldError: ENTITY_ENDERMEN_TELEPORT
        at bammerbom.ultimatecore.bukkit.resources.utils.LocationUtil.playEffect(LocationUtil.java:401) ~[?:?]
        at bammerbom.ultimatecore.bukkit.resources.utils.LocationUtil.teleport(LocationUtil.java:359) ~[?:?]
        at bammerbom.ultimatecore.bukkit.resources.utils.LocationUtil.teleportUnsafe(LocationUtil.java:383) ~[?:?]
        at bammerbom.ultimatecore.bukkit.commands.CmdWarp.run(CmdWarp.java:94) ~[?:?]
        at bammerbom.ultimatecore.bukkit.UltimateCommands.onCmd(UltimateCommands.java:215) ~[?:?]
        at bammerbom.ultimatecore.bukkit.UltimateCore.onCommand(UltimateCore.java:182) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.jar:git-Paper-129]
        ... 15 more
`
**Using PaperSpigot 1.13**
**Note that the plugin works but spams the console**

**Comment by KoffieMeister** [comment]
It seems that you are using the bukkit version of UC, this version is not working at the moment since it was last updated in 2016. The sponge version is working, so you could try to switch to that. An update of the bukkit version will not happen soon.
